# Generated by Django 5.1.1 on 2024-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ndvi_plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIFFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='tiff_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
