# Generated by Django 5.1.1 on 2024-10-18 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_ndviplot_tiffimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NDVIPlot',
        ),
        migrations.DeleteModel(
            name='TIFFImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='tiff_files/'),
        ),
    ]
