# Generated by Django 5.1.1 on 2024-10-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_ndviplot_tiffimage_delete_image_delete_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='water_plots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
